# ==========================================
#  Application Docker Configuration
# ==========================================

spring:
  ssl:
    bundle:
      jks:
        microservice-bundle:
          keystore:
            location: "file:/app/services/${spring.application.name}/${spring.application.name}.p12"
          truststore:
            location: "file:/app/truststore/truststore.p12"

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: https://eureka-server:${EUREKA_PORT}/eureka/
    tls:
      key-store: "file:/app/services/${spring.application.name}/${spring.application.name}.p12"
      trust-store: "file:/app/truststore/truststore.p12"