# ==========================================
#  Application Dev Configuration
# ==========================================

server:
  ssl:
    trust-store: file:${CERT_DIR_PATH}/truststore/truststore.p12
    key-store: file:${CERT_DIR_PATH}/services/${spring.application.name}/${spring.application.name}.p12

eureka:
  instance:
    hostname: localhost
  client:
    tls:
      trust-store: file:${CERT_DIR_PATH}/truststore/truststore.p12
      key-store: file:${CERT_DIR_PATH}/services/${spring.application.name}/${spring.application.name}.p12
    service-url:
      defaultZone: https://localhost:${EUREKA_PORT}/eureka/