# ==========================================
#  Application Docker Configuration
# ==========================================

server:
  ssl:
    trust-store: file:/app/truststore/truststore.p12
    key-store: file:/app/services/${spring.application.name}/${spring.application.name}.p12

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    tls:
      trust-store: file:/app/truststore/truststore.p12
      key-store: file:/app/services/${spring.application.name}/${spring.application.name}.p12
    service-url:
      defaultZone: https://eureka-server:${EUREKA_PORT}/eureka/