# ==========================================
# GATEWAY ROUTING & EDGE CONFIGURATION
# ==========================================

server:
  port: ${GATEWAY_PORT}
  ssl:
    client-auth: none

spring:
# == Redis Session Management ==
  session:
    data:
      redis:
        namespace: "transcendence:sessions"
        save-mode: on-set-attribute
        repository-type: indexed
  data:
    redis:
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
# == WebClient Configuration for Inter-Service Communication ==
  cloud:
    gateway:
      # == SSL Configuration for WebClient ==
      httpclient:
        ssl:
          # Trust our internal CA for all outbound calls to backend services
          trust-store: "file:${CERT_DIR_PATH}/truststore/truststore.p12"
          trust-store-type: PKCS12
          trust-store-password: "${CERT_PASSWORD}"
          # Present gateway's client cert (mTLS client side)
          key-store-type: PKCS12
          key-password: "${CERT_PASSWORD}"
          key-store-password: "${CERT_PASSWORD}"
      server:
        webflux:

        # == Discovery Configuration ==
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
        # == Route Configuration ==
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2
