# ==========================================
#  Gateway Dev Configuration
# ==========================================

spring:
  data:
    redis:
      host: localhost
  cloud:
    gateway:
      server:
        webflux:
      # == SSL Configuration for WebClient (Reactor Netty httpclient) ==
          httpclient:
            ssl:
              key-store: "file:${CERT_DIR_PATH}/services/${spring.application.name}/${spring.application.name}.p12"
              trusted-x509-certificates:
                - "file:${CERT_DIR_PATH}/rootCA/rootCA.crt"
          
custom:
  jwt:
    public-key-location: file:${CERT_DIR_PATH}/jwt/jwt_public.pem
    private-key-location: file:${CERT_DIR_PATH}/jwt/jwt_private_pkcs8.pem