# ==========================================
# Global Eureka Server Configuration
# ==========================================

server:
  port: 8761
  ssl:
    client-auth: want # Allow browsers to view the UI dashboard easily without requiring an mTLS certificate

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false