# ==========================================
# AUTH SERVICE DEVELOPMENT OVERRIDES
# ==========================================

app:
  error-docs-url: "https://localhost:8080/docs/errors#"  

spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${DB_NAME}
  
  data:
    redis:
      host: localhost
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://localhost:${GATEWAY_PORT}/.well-known/jwks.json"