spring:
  application:
    name: gateway
  session:
    data:
      redis:
        namespace: "transcendence:session"
        save-mode: on-set-attribute
        repository-type: indexed

server:
  port: 8080

