# ==========================================
#  Gateway Dev Configuration
# ==========================================

spring:
  data:
    redis:
      host: localhost
          
custom:
  jwt:
    public-key-location: file:${CERT_DIR_PATH}/jwt/jwt_public.pem
    private-key-location: file:${CERT_DIR_PATH}/jwt/jwt_private_pkcs8.pem