server:
  ssl:
    enabled: true
    key-store: "file:${user.home}/1337/Microservices/certs/eureka-server.p12"
    key-store-password: ${CERT_PASSWORD:password}
    trust-store: "file:${user.home}/1337/Microservices/certs/truststore.p12"
    trust-store-password: ${CERT_PASSWORD:password}

