#server:
#  ssl:
#    enabled: true
#    key-store: "file:/app/certs/eureka-server.p12"
#    key-store-password: ${CERT_PASSWORD}
#    trust-store: "file:/app/certs/truststore.p12"
#    trust-store-password: ${CERT_PASSWORD}
#
#eureka:
#  instance:
#    hostname: eureka-server
#
#
