# ==========================================
# AUTH SERVICE DOCKER OVERRIDES
# ==========================================

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:${POSTGRES_PORT}/${DB_NAME}
  
  data:
    redis:
      host: redis-container
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://gateway:${GATEWAY_PORT}/.well-known/jwks.json"
