# ==========================================
#  Application Docker Configuration
# ==========================================

spring:
  ssl:
    bundle:
      jks:
        microservice-bundle:
          keystore:
            location: "file:/app/certs/services/${spring.application.name}/${spring.application.name}.p12"
          truststore:
            location: "file:/app/certs/truststore/truststore.p12"
  kafka:
    bootstrap-servers: "kafka:9092"

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: https://eureka-server:8761/eureka/
    tls:
      key-store: "file:/app/certs/services/${spring.application.name}/${spring.application.name}.p12"
      trust-store: "file:/app/certs/truststore/truststore.p12"