# ==========================================
#  Application Dev Configuration
# ==========================================
# Use dynamic random ports locally to prevent port conflict issues
server:
  port: 0

spring:
  ssl:
    bundle:
      jks:
        microservice-bundle:
          keystore:
             location: "file:${CERT_DIR_PATH:../../certs}/services/${spring.application.name}/${spring.application.name}.p12"
          truststore:
             location: "file:${CERT_DIR_PATH:../../certs}/truststore/truststore.p12"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      key-store: "file:${CERT_DIR_PATH:../../certs}/services/${spring.application.name}/${spring.application.name}.p12"
      trust-store: "file:${CERT_DIR_PATH:../../certs}/truststore/truststore.p12"